version: "3"
services:
  stream9build:
    volumes:
      - rpm9stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS9

volumes:
  rpm9stream:
    name: rpm9stream
