services:
  stream9build:
    volumes:
      - rpm9stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $OS9
  rocky9build:
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL9

volumes:
  rpm9stream:
    name: rpm9stream
  rpm9rocky:
    name: rpm9rocky
