name: RPM build
on: [push]
env:
  ARTIFACTORY_URL: https://rpmb.jfrog.io
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  BINTRAY_REPO: custom
  RL9: 9.6.20250531
  RL9TAG: 9.6.20250531
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - compose-file: docker-compose.yml
            build: rocky9build
            uploader: rocky9bintray
            repo_path: rocky/9
    env:
      BUILD_COMPOSE_FILE: ${{ matrix.compose-file }}
      BUILD: ${{ matrix.build }}
      UPLOADER: ${{ matrix.uploader }}
      REPO_PATH: ${{ matrix.repo_path }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: docker compose -f docker-compose.yml build --no-cache $BUILD
      - run: docker compose -f docker-compose.yml up --exit-code-from $BUILD $BUILD
      - run: docker compose -f rpmbuild/docker-compose.yml pull $UPLOADER
      - run: docker compose -f rpmbuild/docker-compose.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e ARTIFACTORY_URL=$ARTIFACTORY_URL -e REPO_PATH=$REPO_PATH $UPLOADER
